name: Build and publish

on:
  push:
    branches:
      - master

env:
  TEST_TAG: test
  LATEST_TAG: latest
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  BUILD-APP:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Setup .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0
      - name: Restore dependencies
        run: dotnet restore
      - name: Build
        run: dotnet build --no-restore
      - name: Test
        run: dotnet test --no-build --verbosity normal

  BUILD-AND-PUBLISH-IMAGE:
    needs: BUILD-APP
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Build and export to Docker
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ECommerce.Client/Dockerfile
          load: true
          tags: ${{ env.TEST_TAG }}

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}-client
          
      - name: Create env for lower case repository name
        run: |
          echo "REPO_LC=${REPO,,}" >>${GITHUB_ENV}
        env:
          REPO: '${{ github.repository }}'

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./ECommerce.Client/Dockerfile
          push: true
          tags: ${{ env.REGISTRY}}/${{ env.REPO_LC }}-client:latest
          labels: ${{ steps.meta.outputs.labels }}